# Use postgres/example user/password credentials
version: "3.8"
services:
    db:
        image: postgres
        # restart: always
        environment: 
            POSTGRES_HOST_AUTH_METHOD: trust
            POSTGRES_DB: better_cupid_dev
        volumes:
            - postgres_data:/var/lib/postgresql/data # persist data even if container shuts down
    node:
        build: .
        environment:
            - NODE_ENV=test
        ports:
            - "4000:4000"
volumes:
    postgres_data: